name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
#  bucket_name: Markel Application
  AWS_REGION: us-east-2
  REMOTE_HOST: ec2-3-142-232-142.us-east-2.compute.amazonaws.com
  REMOTE_USER: ec2-user

permissions:
  contents: read
  id-token: write

jobs:
  build:
    defaults:
      run:
        working-directory: App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
    - name: Build  
      if: success()      
      run: dotnet build --configuration Release --no-restore
  build-and-test:
    runs-on: ubuntu-latest    
    if: success()  
    needs: [build]    
    steps:
    - name: Restore dependencies
      if: success()  
      run: dotnet restore
    - name: Build
      if: success()  
      run: dotnet build --no-restore
    - name: Test
      if: success()      
      run: dotnet test --no-build --verbosity normal
