name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
#  bucket_name: Markel Appl
  AWS_REGION: us-east-2
  REMOTE_HOST: ec2-3-142-232-142.us-east-2.compute.amazonaws.com
  REMOTE_USER: ec2-user

permissions:
  contents: read
  id-token: write

jobs:
  build:
    defaults:
      run:
        working-directory: App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      if: success()  
      run: dotnet restore
    - name: Build
      if: success()  
      run: dotnet build --no-restore
    - name: Test
      if: success()      
      run: dotnet test --no-build --verbosity normal
