name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
#  bucket_name: Markel Appl
  AWS_REGION: us-east-2
  REMOTE_HOST: ec2-3-142-232-142.us-east-2.compute.amazonaws.com
  REMOTE_USER: ec2-user

permissions:
  contents: read
  id-token: write

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $REMOTE_HOST
            User $REMOTE_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ env.HOST_NAME }}
          SSH_USER: ${{ env.REMOTE_USER }}
          SSH_KEY: ${{ secrets.MARKELPRIVATEKEY }} 
      - name: List home directory
        run: ssh ec2 'ls -la'
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name : Checkout
        uses: actions/checkout@v3
      - name: Setup working directory
        working-directory: ./App
        run: dotnet test ./Markel.Claims.Service.sln --configuration Release --no-restore --verbosity normal        
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: dotnet publish
        run: |
         dotnet publish -c Release -o Markel.Claims.Service 
